# Сборка
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft 26.x требует Java 25 — путь прописан явно,
# потому что системный JAVA_HOME указывает на другую версию.
org.gradle.java.home=C:/Program Files/Microsoft/jdk-25.0.4.101-hotspot

# Fabric
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.157.0+26.2

# Мод
version=1.2.3
group=dev.d3sound
